

# TODO: clang builds
language: python
sudo: required
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  # Force use of modern pip and setuptools
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -r requirements.txt --verbose
  - python -V
  - python -c "import platform; print(platform.python_compiler())"

install:
  - gcc-6 --version
  - gcc --version
  # The TravisCI "Trusty" environments do not have a default $CC set
  - export CC="gcc-6" CXX="g++-6" 
  # And pip does not respect $CC
  - python setup.py install
  
script:
  - mkdir empty
  - cd empty
  - python -c "import sys;import cpufeature; sys.exit(bool(cpufeature.CPUFeature))"

notifications:
  email: false


