name: Build

on: [push, pull_request]

env:
  # CIBW_BUILD_VERBOSITY: 1
  # CIBW_TEST_REQUIRES: pytest
  # Neither {project} nor {package} contain the extension.
  # Instead it's generally in some `/tmp/tmp.SJAhduyLic/venv/lib/python3.6/site-packages/cpufeature` or similar folder.
  # I suppose we could invoke pytest via `subprocess`?
  # CIBW_TEST_COMMAND: ls -altr {project}/cpufeature && ls -altr {package}/cpufeature && python -c "import os, sys, cpufeature; d = os.path.dirname(cpufeature.__file__); print(d); print(os.listdir(d)); sys.exit(0 if cpufeature.test().wasSuccessful() else 1)"
  CIBW_TEST_COMMAND: python -c "import sys, cpufeature; sys.exit(0 if cpufeature.test().wasSuccessful() else 1)"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.10'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels for CPython 3.8
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp38-*"

      - name: Build wheels for CPython 3.9
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp39-*"

      - name: Build wheels for CPython 3.10
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp310-*"

      - name: Build wheels for CPython 3.11
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp311-*"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl