name: Build

on: [push, pull_request]

env:
  # CIBW_BUILD_VERBOSITY: 1
  CIBW_TEST_COMMAND: python -c "import sys, cpufeature; sys.exit(0 if cpufeature.test().wasSuccessful() else 1)"
  CIBW_SKIP: "*-macosx_arm64 *-macosx_universal2 *-win_arm64"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-13]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.10"

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels for CPython 3.8
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp38-*"

      - name: Build wheels for CPython 3.9
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp39-*"

      - name: Build wheels for CPython 3.10 and above
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp310-*"

      - run: ls ./wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: wheelhouse-${{ matrix.os }}
          path: ./wheelhouse/*.whl
