name: Build

on: [push, pull_request]

env:
  CIBW_BUILD_VERBOSITY: 1
  CIBW_TEST_REQUIRES: pytest
  CIBW_TEST_COMMAND: ls -altr {project} && ls -altr {package} && python -c "import os; import cpufeature; d = os.path.dirname(cpufeature.__file__); print(d); print(os.listdir(d))"
  # CIBW_TEST_COMMAND: pytest {project}/cpufeature/test_cpufeature.py

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.6.4

      - name: Build wheels for CPython 3.6
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp36-*"

      - name: Build wheels for CPython 3.7
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp37-*"

      - name: Build wheels for CPython 3.8
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp38-*"

      - name: Build wheels for CPython 3.9
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp39-*"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl